language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  matrix:
    - TYPO3_VERSION=7.6.*

matrix:
  include:
    - php: 7.0
      env: TYPO3_VERSION=8.7.*
    - php: 7.1
      env: TYPO3_VERSION=8.7.*
  allow_failures:
    - env: TYPO3_VERSION=8.7.*

sudo: false

addons:
  apt:
    packages:
      - parallel
      - imagemagick

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  - cd .Build
  - composer require typo3/cms=$TYPO3_VERSION
  - export TYPO3_PATH_WEB=$TRAVIS_BUILD_DIR/.Build/web;
  - cd $TRAVIS_BUILD_DIR

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} \;
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit --colors --configuration .Build/UnitTests.xml;
  - >
    echo;
    echo "Running functional tests";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseName="typo3";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    export IM="1";
    export IM_PATH="/usr/bin/";
    export IM_PATH_LZW="/usr/bin/";
    export IM_VRSION_5="gm";
    .Build/bin/phpunit --process-isolation --colors --configuration .Build/FunctionalTests.xml;
